In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
a = np.array([1,2,3])

In [16]:
print type(a), a.shape, a[0],a[1],a[2]
a[0] = 5
print a
b = np.array([[1,2,3],[3,4,5]])
print b,b.shape
print b[0,1]

<type 'numpy.ndarray'> (3,) 5 2 3
[5 2 3]
[[1 2 3]
 [3 4 5]] (2, 3)
2


In [25]:
print np.zeros((2,2))
print np.ones((2,2))
print np.random.random((2,2))
print np.eye(4)
print np.full((3,4),7)

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]
 [ 1.  1.]]
[[ 0.40098137  0.44058979]
 [ 0.28266791  0.69636939]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 7.  7.  7.  7.]
 [ 7.  7.  7.  7.]
 [ 7.  7.  7.  7.]]


/Users/Siddhesh/anaconda2/lib/python2.7/site-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full((3, 4), 7) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


In [30]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print a.shape
b = a[:2,:3]
print a
print b
b[0,0] = 10
print a[0,0]

(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]
10


In [31]:
row_rank1 = a[1,:]
row_rank2 = a[1:2,:]
print row_rank1, row_rank1.shape
print row_rank2, row_rank2.shape

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [37]:
print a[[0,1,0],[1,2,0]]
print np.array(a[[0,1,0],[1,2,0]])
print a[[0,0],[0,0]]

[2 7 1]
[2 7 1]
[1 1]


In [45]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([2,0,1,2])
a[np.arange(4),b] += 5
print a

[[ 1  2  8]
 [ 9  5  6]
 [ 7 13  9]
 [10 11 17]]


In [49]:
a = np.array([[1,2], [3, 4], [5, 6]])
b_idx= a>2
print b_idx
print a[b_idx]
print a[a>2]

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [54]:
x = np.array([1,2])
print x.dtype
x = np.array([1.0,2.0])
print x.dtype
x = np.array([1.,2.])
print x.dtype
x = np.array([1,2],dtype=np.float32)
print x.dtype
print x

int64
float64
float64
float32
[ 1.  2.]


In [74]:
x = np.array([[1,2],[2,3]],dtype=np.float32)
y = np.array([[1.5,4],[6,7]],dtype=np.float64)
print np.add(x,y)
print np.subtract(x,y)
print np.multiply(x,y)
print np.divide(x,y)
print np.sqrt(x)

[[  2.5   6. ]
 [  8.   10. ]]
[[-0.5 -2. ]
 [-4.  -4. ]]
[[  1.5   8. ]
 [ 12.   21. ]]
[[ 0.66666667  0.5       ]
 [ 0.33333333  0.42857143]]
[[ 1.          1.41421354]
 [ 1.41421354  1.73205078]]


In [85]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
print v.dot(w)
print np.dot(v,w)
print x.dot(y)
print np.dot(x,y)
print np.sum(x,axis =0)
print np.sum(x,axis =1)

219
219
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[4 6]
[3 7]


In [87]:
x = np.array([[1,2], [3,4]])
print x
print x.T

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [104]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print a.reshape(-1)
print a.ravel()
print a.flatten()
#Difference between ravel and flatten is that ravel will return a view of the array and flatten will return a copy

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [109]:
a = np.ones((3,4,5,6))
print a.shape
print np.rollaxis(a,1,3).shape

(3, 4, 5, 6)
(3, 5, 4, 6)


In [122]:
a= np.arange(5)
print a
print a.shape
print np.tile(a,(1,2,2))
a = np.ones((3,4,5,6))
print a.shape
print np.tile(a,(2,2)).shape
a = np.array([1,2,3])


[0 1 2 3 4]
(5,)
[[[0 1 2 3 4 0 1 2 3 4]
  [0 1 2 3 4 0 1 2 3 4]]]
(3, 4, 5, 6)
(3, 4, 10, 12)
(1, 3)


In [143]:
b = np.array([[1, 2], [3, 4]])
print b.shape
print np.tile(b,2)
np.tile(b, (2, 2))

(2, 2)
[[1 2 1 2]
 [3 4 3 4]]


array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])

In [141]:
a= np.arange(3)
print a
print np.tile(a,(2,2,2))

[0 1 2]
[[[0 1 2 0 1 2]
  [0 1 2 0 1 2]]

 [[0 1 2 0 1 2]
  [0 1 2 0 1 2]]]


In [146]:
a = np.arange(3)
b = np.arange(9).reshape(3,3)
print b,a+b

[[0 1 2]
 [3 4 5]
 [6 7 8]] [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [156]:
v = np.array([1,2,3]) 
w = np.array([4,5])
print np.dot(v.reshape(3,1),w.reshape(1,2))

[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
x = np.arange(0, 3 * np.pi, 0.1)
y = np.sin(x)
plt.plot(x,y)
plt.show()

In [12]:
W = np.random.randn(5,10)
x = np.random.randn(10,3)
D = W.dot(x)
dD = np.random.randn(*D.shape)
dW = dD.dot(x.T)
dX = W.T.dot(dD)


In [19]:
x = np.random.randn(5,4)
print np.mean(x,axis=1)

[ 0.53122023  0.1329313   0.27480152 -0.51287051 -0.23895199]
